# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92d996133909490f1e533084dd1faa1e1486dc66eea232249f8087bdf6196ceb3aca6567a0c9edbde38223c5e23ba46c7f5a3f29d13a08e0c12ac47f726ac5b5

test:
  secret_key_base: 84f90aac58bc96162de3ba2f72e00beaa36402ff7092af123f39f7d9927a6367e9a1302fca196e13e16baec697e16b061a6742ba0dc2bbfd532cc082f7610d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
